### ISSUE TITLE
Ou est la racine?

### ISSUE THREAD

**Issue by Cimmerian-Iter** [Ooggle/Boot9Strap-gm9-install-script#1]
Dans le readme y a marqué extraire le zip a la racine
mais ma carte sd c'est pas un arbre. 
que faire?

**Comment by Ooggle** [comment]
Dans les systèmes de fichiers informatiques, la racine des répertoires ou dossiers (appelé aussi la racine d'un disque) est la base des répertoires dans la hiérarchie. Il peut être imagé par un tronc d'un arbre, c'est-à-dire le point de départ de toutes les branches (de tous les répertoires/dossiers).

Pour reprendre l'analogie avec le monde réel, dans une armoire à classeurs (ou trieur), les tiroirs sont représentés comme le plus haut niveau des sous-répertoires du système de fichiers, et la pièce peut être considérée comme étant le répertoire racine. Le répertoire racine peut contenir d'autres répertoires mais il ne peut être contenu, du moins dans ce système de fichiers.

**Comment by Ooggle** [comment]
source : [Wikipedia](https://fr.wikipedia.org/wiki/R%C3%A9pertoire_racine)
